name: async_cable
description: Async/stream-oriented implementation of the Rails ActionCable protocol for Dart & Flutter.
version: 1.1.3
homepage: https://github.com/DelivereasyNZ/async_cable

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mocktail: ^0.3.0
